name: YouTube Highlight (self-hosted, Windows - no browser kill)

on:
  workflow_dispatch:
    inputs:
      videoId:
        description: "YouTube Video ID (e.g., dQw4w9WgXcQ)"
        required: true
        type: string
      browser:
        description: "Browser to read cookies from (edge or chrome). Prefer one you can close."
        required: true
        default: "edge"
        type: choice
        options: [edge, chrome]
      profile:
        description: 'Browser profile folder (e.g., "Default", "Profile 1"). If unsure, leave as Default.'
        required: false
        default: "Default"
        type: string
      format:
        description: "yt-dlp format"
        required: false
        default: 'bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4]/bv*+ba/b'
        type: string

jobs:
  highlight:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Allow PowerShell scripts (CurrentUser)
        shell: powershell
        run: |
          Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy RemoteSigned -Force

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install yt-dlp
        shell: powershell
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade yt-dlp

      - name: Check ffmpeg availability
        shell: powershell
        run: |
          if (Get-Command ffmpeg -ErrorAction SilentlyContinue) {
            ffmpeg -version | Select-Object -First 1
          } else {
            Write-Host "WARNING: ffmpeg not found on PATH. If a merge is required, install ffmpeg or add it to PATH."
          }

      - name: Download source video (live cookies; no browser kill)
        shell: powershell
        run: |
          $ErrorActionPreference = "Stop"

          $VIDEO_ID = '${{ inputs.videoId }}'
          $BROWSER  = '${{ inputs.browser }}'.ToLower()
          $PROFILE  = '${{ inputs.profile }}'
          $FMT      = '${{ inputs.format }}'

          Write-Host "Requested browser=$BROWSER, profile=$PROFILE"

          function Resolve-Profile {
            param([string]$Browser, [string]$Profile)

            $bases = @()
            if ($Browser -eq 'chrome') {
              $bases += (Join-Path $env:LOCALAPPDATA  'Google\Chrome\User Data')
              $bases += (Join-Path $env:APPDATA       'Google\Chrome\User Data')
            } elseif ($Browser -eq 'edge') {
              $bases += (Join-Path $env:LOCALAPPDATA  'Microsoft\Edge\User Data')
              $bases += (Join-Path $env:APPDATA       'Microsoft\Edge\User Data')
            } else { throw "Unsupported browser: $Browser" }

            foreach ($base in $bases) {
              if (-not (Test-Path $base)) { continue }

              $profPath = Join-Path $base $Profile
              if (Test-Path $profPath) { return @{ Path=$profPath; Name=$Profile; Base=$base } }

              $candidates = Get-ChildItem -Path $base -Directory -ErrorAction SilentlyContinue |
                Where-Object { $_.Name -match '^(Default|Profile \d+)$' }

              $scored = foreach ($d in $candidates) {
                $cookie1 = Join-Path $d.FullName 'Network\Cookies'
                $cookie2 = Join-Path $d.FullName 'Cookies'
                [pscustomobject]@{ Name=$d.Name; Full=$d.FullName; HasCookies=(Test-Path $cookie1) -or (Test-Path $cookie2) }
              }

              $pick = $scored | Sort-Object -Property @{Expression='HasCookies';Descending=$true}, Name | Select-Object -First 1
              if ($pick) { return @{ Path=$pick.Full; Name=$pick.Name; Base=$base } }
            }

            return $null
          }

          # 1) Resolve profile path
          $resolved = Resolve-Profile -Browser $BROWSER -Profile $PROFILE
          if ($null -eq $resolved) {
            Write-Host "Could not locate a profile."
            if ($BROWSER -eq 'chrome') {
              Write-Host ("Checked: " + (Join-Path $env:LOCALAPPDATA 'Google\Chrome\User Data') + " and " + (Join-Path $env:APPDATA 'Google\Chrome\User Data'))
            } else {
              Write-Host ("Checked: " + (Join-Path $env:LOCALAPPDATA 'Microsoft\Edge\User Data') + " and " + (Join-Path $env:APPDATA 'Microsoft\Edge\User Data'))
            }
            Write-Host "Open chrome://version or edge://version and copy the tail of 'Profile Path' (e.g. 'Default' or 'Profile 1')."
            throw "Browser profile '$PROFILE' not found for $BROWSER"
          }

          Write-Host ("Resolved profile: " + $resolved.Name + " at " + $resolved.Path)

          # 2) Ensure target browser isn't running (we won't kill it; just fail with a clear message)
          $procName = if ($BROWSER -eq 'chrome') { 'chrome' } else { 'msedge' }
          $procs = Get-Process -Name $procName -ErrorAction SilentlyContinue
          if ($procs) {
            Write-Host "The selected browser ($procName) is currently running."
            Write-Host "To avoid the locked cookie database error, please close ALL windows of $procName for the duration of the run."
            Write-Host "Tip: Use a secondary browser for Actions (e.g., Edge) while you keep your main browser open."
            throw "Cookie DB is locked because $procName is running."
          }

          # 3) Build cookies-from-browser arg and download
          $CFB = $BROWSER + ':' + $resolved.Name
          Write-Host "cookies-from-browser = $CFB"

          yt-dlp --cookies-from-browser "$CFB" `
                 --extractor-args "youtube:player_client=android" `
                 -o "input.%(ext)s" -f "$FMT" `
                 "https://www.youtube.com/watch?v=$VIDEO_ID"

          Write-Host "Downloaded files:"
          Get-ChildItem -Force | Format-Table -AutoSize

      - name: Upload source artifact
        uses: actions/upload-artifact@v4
        with:
          name: source-video
          path: |
            input*.mp4
            input*.mkv
            input*.webm
          if-no-files-found: warn
