name: YouTube Highlight (Windows, self-hosted, Firefox)

on:
  workflow_dispatch:
    inputs:
      videoId:
        description: "YouTube Video ID (e.g., dQw4w9WgXcQ)"
        required: true
        type: string
      profile:
        description: 'Firefox profile name from about:profiles (e.g., "xxxxx.default-release")'
        required: true
        default: "default-release"
        type: string
      format:
        description: "yt-dlp format"
        required: false
        default: 'bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4]/bv*+ba/b'
        type: string

jobs:
  highlight:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Allow PowerShell scripts (CurrentUser)
        shell: powershell
        run: Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy RemoteSigned -Force

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install yt-dlp
        shell: powershell
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade yt-dlp

      - name: Check ffmpeg (optional)
        shell: powershell
        run: |
          if (Get-Command ffmpeg -ErrorAction SilentlyContinue) {
            ffmpeg -version | Select-Object -First 1
          } else {
            Write-Host "WARNING: ffmpeg not found on PATH. If a merge is required, install ffmpeg or add it to PATH."
          }

      - name: Download with Firefox cookies (no DPAPI)
        shell: powershell
        run: |
          $ErrorActionPreference = "Stop"
          $VIDEO_ID = '${{ inputs.videoId }}'
          $PROFILE  = '${{ inputs.profile }}'
          $FMT      = '${{ inputs.format }}'

          # Ensure Firefox is closed (no background)
          $procs = Get-Process -Name firefox -ErrorAction SilentlyContinue
          if ($procs) {
            Write-Error "Firefox is running. Please close all Firefox windows before starting the run."
            exit 1
          }

          # Validate profile folder exists under %APPDATA%\Mozilla\Firefox\Profiles
          $base = Join-Path $env:APPDATA 'Mozilla\Firefox\Profiles'
          if (-not (Test-Path (Join-Path $base $PROFILE))) {
            Write-Host "Profile '$PROFILE' not found under $base"
            Write-Host "Open about:profiles and copy the *folder name* (e.g., 'xxxxx.default-release')."
            exit 1
          }

          $CFB = "firefox:$PROFILE"
          Write-Host "Using cookies-from-browser = $CFB"

          yt-dlp --cookies-from-browser $CFB `
                 --extractor-args "youtube:player_client=android" `
                 -o "input.%(ext)s" -f $FMT `
                 "https://www.youtube.com/watch?v=$VIDEO_ID"

          Write-Host "Files:"
          Get-ChildItem -Force | Format-Table -AutoSize

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: source-video
          path: |
            input*.mp4
            input*.mkv
            input*.webm
          if-no-files-found: warn
