name: YouTube Highlight (self-hosted, Windows)

on:
  workflow_dispatch:
    inputs:
      videoId:
        description: "YouTube Video ID (e.g., dQw4w9WgXcQ)"
        required: true
        type: string
      browser:
        description: "Browser to read cookies from (chrome or edge)"
        required: true
        default: "chrome"
        type: choice
        options: [chrome, edge]
      profile:
        description: 'Browser profile folder name (e.g., "Default" or "Profile 1")'
        required: false
        default: "Default"
        type: string
      format:
        description: "yt-dlp format (leave default unless needed)"
        required: false
        default: 'bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4]/bv*+ba/b'
        type: string

jobs:
  highlight:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Allow PowerShell scripts (CurrentUser)
        shell: powershell
        run: |
          Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy RemoteSigned -Force

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install yt-dlp
        shell: powershell
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade yt-dlp

      - name: Check ffmpeg availability
        shell: powershell
        run: |
          if (Get-Command ffmpeg -ErrorAction SilentlyContinue) {
            ffmpeg -version | Select-Object -First 1
          } else {
            Write-Host "WARNING: ffmpeg not found on PATH. If a merge is required, install ffmpeg or add it to PATH."
          }

      - name: Download source video (live cookies from local browser)
        shell: powershell
        run: |
          $ErrorActionPreference = "Stop"

          $VIDEO_ID = '${{ inputs.videoId }}'
          $BROWSER  = '${{ inputs.browser }}'.ToLower()
          $PROFILE  = '${{ inputs.profile }}'
          $FMT      = '${{ inputs.format }}'

          Write-Host "Using browser=$BROWSER, profile=$PROFILE"

          # Resolve expected profile path and validate it exists
          if ($BROWSER -eq 'chrome') {
            $base = Join-Path $env:LOCALAPPDATA 'Google\Chrome\User Data'
          } elseif ($BROWSER -eq 'edge') {
            $base = Join-Path $env:LOCALAPPDATA 'Microsoft\Edge\User Data'
          } else {
            throw "Unsupported browser: $BROWSER"
          }

          $profPath = Join-Path $base $PROFILE
          Write-Host "Expecting profile folder at: $profPath"
          if (-not (Test-Path $profPath)) {
            Write-Host "Profile folder not found at: $profPath"
            Write-Host "Open chrome://version or edge://version and copy the tail of 'Profile Path' (e.g. 'Default' or 'Profile 1')."
            throw "Browser profile '$PROFILE' not found."
          }

          # Build cookies-from-browser argument safely (avoid interpolation issues with :)
          $CFB = $BROWSER + ':' + $PROFILE
          Write-Host "cookies-from-browser = $CFB"

          yt-dlp --cookies-from-browser "$CFB" `
                 --extractor-args "youtube:player_client=android" `
                 -o "input.%(ext)s" -f "$FMT" `
                 "https://www.youtube.com/watch?v=$VIDEO_ID"

          Write-Host "Downloaded files:"
          Get-ChildItem -Force | Format-Table -AutoSize

      - name: Upload source artifact
        uses: actions/upload-artifact@v4
        with:
          name: source-video
          path: |
            input*.mp4
            input*.mkv
            input*.webm
          if-no-files-found: warn
