name: YouTube Highlight (Windows + Firefox, WEB client)

on:
  workflow_dispatch:
    inputs:
      videoId:
        description: "YouTube Video ID (e.g., dQw4w9WgXcQ)"
        required: true
        type: string
      profile:
        description: 'Firefox profile folder from about:profiles (e.g., "yov4tydr.default-release-3")'
        required: true
        default: "yov4tydr.default-release-3"
        type: string
      format:
        description: "yt-dlp format selector"
        required: false
        default: 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best'
        type: string

jobs:
  highlight:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Allow PowerShell scripts (CurrentUser)
        shell: powershell
        run: Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy RemoteSigned -Force

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install yt-dlp
        shell: powershell
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade yt-dlp

      - name: Ensure Firefox is closed
        shell: powershell
        run: |
          if (Get-Process firefox -ErrorAction SilentlyContinue) {
            Write-Error "Firefox is running. Please close all Firefox windows before starting the run."
            exit 1
          }

      - name: Validate Firefox profile
        shell: powershell
        run: |
          $base = Join-Path $env:APPDATA 'Mozilla\Firefox\Profiles'
          $prof = '${{ inputs.profile }}'
          $path = Join-Path $base $prof
          Write-Host "Checking profile at: $path"
          if (-not (Test-Path $path)) {
            Write-Error "Firefox profile '$prof' not found under $base. Open about:profiles and copy the folder name."
            exit 1
          }

      - name: List formats (WEB client) and save output
        shell: powershell
        run: |
          $CFB = "firefox:${{ inputs.profile }}"
          $URL = "https://www.youtube.com/watch?v=${{ inputs.videoId }}"
          Write-Host "Using cookies-from-browser = $CFB"
          Write-Host "FORCING WEB CLIENT"
          yt-dlp --verbose --cookies-from-browser $CFB `
                 --extractor-args "youtube:player_client=web" `
                 -F $URL | Tee-Object -FilePath list-formats.txt

      - name: Download (WEB client)
        shell: powershell
        run: |
          $CFB = "firefox:${{ inputs.profile }}"
          $URL = "https://www.youtube.com/watch?v=${{ inputs.videoId }}"
          $FMT = '${{ inputs.format }}'
          yt-dlp --verbose --cookies-from-browser $CFB `
                 --extractor-args "youtube:player_client=web" `
                 -o "input.%(ext)s" -f $FMT `
                 $URL

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: yt-debug-and-source
          path: |
            list-formats.txt
            input*.mp4
            input*.mkv
            input*.webm
          if-no-files-found: warn
