name: YouTube-Highlight-Drive

on:
  workflow_dispatch:
    inputs:
      videoId:
        description: "YouTube video ID"
        required: true
      title:
        description: "Title (unused)"
        required: true
        default: "Test"
      channel:
        description: "Channel name (unused)"
        required: true
        default: "Test"
      channelId:
        description: "Channel ID (unused)"
        required: true
        default: "UC0000000000000000000000"
      publishedAt:
        description: "ISO time (unused)"
        required: true
        default: "2024-01-01T00:00:00Z"

env:
  FONT_URL: https://github.com/googlefonts/noto-fonts/raw/main/hinted/ttf/NotoNaskhArabic/NotoNaskhArabic-Regular.ttf
  GDRIVE_REMOTE: ${{ secrets.GDRIVE_REMOTE }}
  GDRIVE_PATH:   ${{ secrets.GDRIVE_PATH }}

jobs:
  highlight:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install system deps (ffmpeg + fonts + rclone)
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg fonts-noto-cjk rclone
          curl -L "$FONT_URL" -o ./NotoNaskhArabic-Regular.ttf

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python requirements
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Restore rclone config from secret
        env:
          RCLONE_CONFIG_CONTENTS: ${{ secrets.RCLONE_CONFIG_CONTENTS }}
        run: |
          mkdir -p ~/.config/rclone
          printf "%s\n" "$RCLONE_CONFIG_CONTENTS" > ~/.config/rclone/rclone.conf
          rclone listremotes || true

      - name: Resolve inputs
        id: meta
        run: |
          echo "videoId=${{ inputs.videoId }}" >> $GITHUB_OUTPUT

      - name: Download source video (yt-dlp)
        run: |
          set -e
          VIDEO_ID='${{ steps.meta.outputs.videoId }}'
          yt-dlp -o "input.%(ext)s" -f "bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4]/bv*+ba/b" "https://www.youtube.com/watch?v=${VIDEO_ID}"
          ls -lah

      - name: Transcribe + select highlight + burn subs
        run: |
          python scripts/process_video.py \
            --input input.mp4 \
            --min-seconds 30 \
            --max-seconds 60 \
            --lang ar \
            --keywords-prefer "قصة,مهم,نصيحة,أفضل,ضحك,سر,خطأ,نجاح,تجربة,لقطة" \
            --keywords-avoid "إعلان,موسيقى,مقدمة,خاتمة" \
            --font ./NotoNaskhArabic-Regular.ttf

      - name: Upload to Google Drive (rclone)
        run: |
          set -e
          VIDEO_ID='${{ steps.meta.outputs.videoId }}'
          START=$(python -c 'import json;print(json.load(open("artifact.json"))["start"])')
          END=$(python -c 'import json;print(json.load(open("artifact.json"))["end"])')
          OUTFILE=$(python -c 'import json;print(json.load(open("artifact.json"))["outfile"])')
          # keep filename simple to avoid quoting issues for now
          DEST="${GDRIVE_REMOTE}:${GDRIVE_PATH%/}/${VIDEO_ID}_${START}-${END}.mp4"
          echo "Uploading $OUTFILE → $DEST"
          rclone copy "$OUTFILE" "$DEST" --progress
          echo "rclone upload OK ✅"
