name: YouTube Highlight Drive (rclone verified)

on:
  workflow_dispatch:
    inputs:
      videoId:
        description: "YouTube video ID (not used in this test)"
        required: true

jobs:
  setup-install-and-rclone:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install system deps (ffmpeg + fonts + rclone)
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg fonts-noto-cjk rclone

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python requirements
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      # ===== RCLONE: restore config from BASE64 secret (robust) =====
      - name: Restore rclone config from base64 secret
        env:
          RCLONE_CONFIG_B64: ${{ secrets.RCLONE_CONFIG_B64 }}
        run: |
          if [ -z "${RCLONE_CONFIG_B64}" ]; then
            echo "Missing secret RCLONE_CONFIG_B64. Please create it with your base64-encoded rclone.conf."; exit 1
          fi
          mkdir -p ~/.config/rclone
          echo "$RCLONE_CONFIG_B64" | base64 -d > ~/.config/rclone/rclone.conf
          # quick sanity
          echo "Remotes found:" && rclone listremotes || true

      - name: Show parsed config (safe/masked by rclone)
        run: |
          echo "---- BEGIN rclone.conf (masked) ----"
          rclone config show || true
          echo "---- END ----"
          echo "Line count:" $(wc -l < ~/.config/rclone/rclone.conf)
          file ~/.config/rclone/rclone.conf || true

      - name: Test Drive access (list or create destination)
        env:
          GDRIVE_REMOTE: ${{ secrets.GDRIVE_REMOTE }}
          GDRIVE_PATH: ${{ secrets.GDRIVE_PATH }}
        run: |
          if [ -z "${GDRIVE_REMOTE}" ] || [ -z "${GDRIVE_PATH}" ]; then
            echo "Missing GDRIVE_REMOTE or GDRIVE_PATH secrets."; exit 1
          fi
          DEST="${GDRIVE_REMOTE}:${GDRIVE_PATH%/}"
          echo "Listing: $DEST"
          rclone lsd "$DEST" || (echo "Creating $DEST" && rclone mkdir "$DEST" && rclone lsd "$DEST")
          echo "rclone OK ✅"
