name: YouTube Highlight (self-hosted)

on:
  workflow_dispatch:
    inputs:
      videoId:
        description: "YouTube Video ID (e.g., dQw4w9WgXcQ)"
        required: true
        type: string
      browser:
        description: "Browser to read cookies from"
        required: true
        default: "chrome"
        type: choice
        options: [chrome, edge]
      profile:
        description: 'Browser profile name (e.g., "Default", "Profile 1")'
        required: false
        default: "Default"
        type: string

jobs:
  highlight:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install yt-dlp
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade yt-dlp

      - name: Install ffmpeg (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          if (Get-Command ffmpeg -ErrorAction SilentlyContinue) {
            "ffmpeg already installed"
          }
          elseif (Get-Command winget -ErrorAction SilentlyContinue) {
            winget install -e --id Gyan.FFmpeg
          }
          else {
            Write-Error "Please install ffmpeg manually or add winget/choco"
          }

      - name: Download source video (from local browser cookies)
        shell: bash
        run: |
          set -euo pipefail
          VIDEO_ID='${{ inputs.videoId }}'
          BROWSER='${{ inputs.browser }}'
          PROFILE='${{ inputs.profile }}'

          echo "Using browser=$BROWSER, profile=$PROFILE"
          yt-dlp --cookies-from-browser "${BROWSER}:profile=${PROFILE}" \
                 --extractor-args "youtube:player_client=android" \
                 -o "input.%(ext)s" \
                 "https://www.youtube.com/watch?v=${VIDEO_ID}"

          ls -lah

      - name: Upload video artifact
        uses: actions/upload-artifact@v4
        with:
          name: source-video
          path: input*
          if-no-files-found: warn
