name: YouTube Highlight Drive (inputs test)

on:
  workflow_dispatch:
    inputs:
      videoId:
        description: "YouTube video ID"
        required: true

jobs:
  echo-input:
    runs-on: ubuntu-latest
    steps:
      - name: Print videoId
        run: echo "videoId=${{ inputs.videoId }}"
