name: YouTube Highlight Drive (rclone direct)

on:
  workflow_dispatch:
    inputs:
      videoId:
        description: "YouTube video ID (test input)"
        required: true

jobs:
  test-drive-access:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install system deps (ffmpeg + fonts + rclone)
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg fonts-noto-cjk rclone

      # Restore rclone config directly from multi-line secret
      - name: Restore rclone config from secret
        env:
          RCLONE_CONFIG_CONTENTS: ${{ secrets.RCLONE_CONFIG_CONTENTS }}
        run: |
          if [ -z "${RCLONE_CONFIG_CONTENTS}" ]; then
            echo "Missing secret RCLONE_CONFIG_CONTENTS"; exit 1
          fi
          mkdir -p ~/.config/rclone
          printf "%s\n" "$RCLONE_CONFIG_CONTENTS" > ~/.config/rclone/rclone.conf
          echo "Config file restored:"
          cat ~/.config/rclone/rclone.conf
          echo "----"
          echo "Remotes found:" && rclone listremotes || true

      - name: Test Drive access
        env:
          GDRIVE_REMOTE: ${{ secrets.GDRIVE_REMOTE }}
          GDRIVE_PATH: ${{ secrets.GDRIVE_PATH }}
        run: |
          if [ -z "${GDRIVE_REMOTE}" ] || [ -z "${GDRIVE_PATH}" ]; then
            echo "Missing GDRIVE_REMOTE or GDRIVE_PATH secrets."; exit 1
          fi
          DEST="${GDRIVE_REMOTE}:${GDRIVE_PATH%/}"
          echo "Listing: $DEST"
          rclone lsd "$DEST" || (echo "Creating $DEST" && rclone mkdir "$DEST" && rclone lsd "$DEST")
          echo "rclone OK ✅"
